import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

export async function generateOrderPDF({ user, order, company }) {
  // Define the path to your custom font files in the public directory
  const fontRegularPath = path.join(
    process.cwd(),
    "public",
    "fonts",
    "OpenSans-Regular.ttf"
  );
  const fontBoldPath = path.join(
    process.cwd(),
    "public",
    "fonts",
    "OpenSans-Bold.ttf"
  );

  // --- Font Loading and Error Handling ---

  if (!fs.existsSync(fontRegularPath)) {
    console.error(
      `PDFKit Error: Regular font file not found at ${fontRegularPath}`
    );
    throw new Error(
      "Required font 'OpenSans-Regular.ttf' not found for PDF generation. Please ensure it's in public/fonts/"
    );
  }

  const doc = new PDFDocument({
    margin: 50,
    font: fontRegularPath,
  });

  doc.registerFont("OpenSans", fontRegularPath);

  if (fs.existsSync(fontBoldPath)) {
    doc.registerFont("OpenSans-Bold", fontBoldPath);
  } else {
    console.warn(
      `PDFKit Warning: Bold font file not found at ${fontBoldPath}. Falling back to regular font for bold text.`
    );
    doc.registerFont("OpenSans-Bold", fontRegularPath);
  }

  const buffers = [];
  doc.on("data", buffers.push.bind(buffers));
  const pdfPromise = new Promise((resolve) => doc.on("end", resolve));

  // --- PDF Content Generation ---

  doc.fontSize(20).text(company.name, { align: "center" }).moveDown(0.5);
  doc
    .fontSize(10)
    .text(`Email: ${company.email}`, { align: "center" })
    .text(`Phone: ${company.phone}`, { align: "center" })
    .text(`Address: ${company.address}`, { align: "center" })
    .moveDown(1);

  doc.fontSize(16).text("Order Confirmation", { align: "center" }).moveDown(1);

  doc.fontSize(12).text(`Order ID: ${order._id}`).moveDown(0.2);
  doc
    .text(`Order Date: ${new Date(order.createdAt).toLocaleDateString()}`)
    .moveDown(0.2);
  doc
    .text(`Customer: ${user.firstName || ""} ${user.lastName || ""}`)
    .moveDown(0.2);
  doc.text(`Email: ${user.email || "N/A"}`).moveDown(0.2);
  doc
    .text(
      `Shipping Address: ${order.shippingAddress.addressLine}, ${order.shippingAddress.city}, ${order.shippingAddress.postalCode}`
    )
    .moveDown(1);

  // Items Table Header
  doc.fontSize(12).text("Items:", { underline: true }).moveDown(0.5);

  doc
    .font("OpenSans-Bold")
    .text("Product Name", 50, doc.y, { width: 200, continued: true })
    .text("Unit Price", 250, doc.y, { width: 100, continued: true })
    .text("Quantity", 350, doc.y, { width: 100, continued: true })
    .text("Total", 450, doc.y, { width: 100 })
    .moveDown(0.5);
  doc.font("OpenSans");

  // Items Rows
  order.items.forEach((item) => {
    const productName = item.productName || "N/A";
    const price = item.price || 0;
    const quantity = item.quantity || 0;
    const itemTotal = price * quantity;

    doc
      .fontSize(10)
      .text(productName, 50, doc.y, { width: 200, continued: true })
      .text(`৳${price.toFixed(2)}`, 250, doc.y, { width: 100, continued: true })
      .text(quantity.toString(), 350, doc.y, { width: 100, continued: true })
      .text(`৳${itemTotal.toFixed(2)}`, 450, doc.y, { width: 100 })
      .moveDown(0.5);
  });

  doc.moveDown(1);

  // Totals Summary
  doc
    .fontSize(12)
    .text("Summary:", { underline: true, align: "right" })
    .moveDown(0.5);
  doc
    .text(
      `Subtotal: ৳${(
        order.totalAmount -
        order.shippingCost -
        order.serviceFee
      ).toFixed(2)}`,
      { align: "right" }
    )
    .moveDown(0.2);
  doc
    .text(`Shipping Cost: ৳${order.shippingCost.toFixed(2)}`, {
      align: "right",
    })
    .moveDown(0.2);
  doc
    .text(`Service Fee: ৳${order.serviceFee.toFixed(2)}`, { align: "right" })
    .moveDown(0.2);
  doc
    .font("OpenSans-Bold")
    .fontSize(14)
    .text(
      `Total Amount: ৳${
        order.totalAmount.toFixed(2) +
        order.shippingCost.toFixed(2) +
        order.serviceFee.toFixed(2)
      }`,
      { align: "right" }
    )
    .moveDown(1);
  doc.font("OpenSans"); // Reset to regular

  // Payment Info
  doc
    .fontSize(10)
    .text(
      `Payment Method: ${order.paymentMethod.replace(/_/g, " ").toUpperCase()}`
    )
    .moveDown(0.2);
  doc.text(`Payment Status: ${order.paymentStatus.toUpperCase()}`).moveDown(1);

  // Footer
  doc
    .fontSize(8)
    .text("Thank you for your business!", { align: "center" })
    .moveDown(0.2);
  doc.text("Generated by Fresh Farm Co.", { align: "center" });

  doc.end();

  await pdfPromise;
  return Buffer.concat(buffers);
}
